"console.log('run $i');" 
"console.log('update $(date)');" 
console.log('run 2');
console.log('run 8');
console.log('run 10');
console.log('run 14');
console.log('run 18');
console.log('run 19');
console.log('run 24');
console.log('run 25');
